language: cpp
sudo: required
dist: trusty

git:
  depth: 200

branches:
  only:
  - master

cache:
  ccache: true
  directories:
  - ${LP3D_LDRAW_DIR}
  - ${LP3D_DIST_DIR_BASE}

env:
  global:
    - LP3D_QT_BASE=59
    - LP3D_LDRAW_DIR=${HOME}/ldraw
    - LP3D_BUILD_FOLDER=${TRAVIS_BUILD_DIR}
    - LP3D_RELEASE_DIR=${LP3D_BUILD_FOLDER}/builds/releases
    - LP3D_LOGS_DIR=${LP3D_RELEASE_DIR}/logs
    - LP3D_3RD_BUILD_FOLDER=${LP3D_BUILD_FOLDER}/..
    - LP3D_DIST_DIR_BASE=${LP3D_3RD_BUILD_FOLDER}/lpub3d_3rdparty_base
    - LP3D_COMPOSE_DIR=builds/linux/docker-compose
    - LP3D_CI_DIR=builds/utilities/ci/travis
    - LP3D_UPLOADER_DIR=builds/utilities/ci/dropbox
    - LP3D_DROPBOX_STORE_DIR=travis-ci/releases
    - LP3D_RELEASE_NAME="LPub3D (Linux/macOS) $(date +'%d.%m.%Y %R')"

before_install:
  - source ${LP3D_CI_DIR}/before_install

install:
  - source ${LP3D_CI_DIR}/install

script:
  - source ${LP3D_CI_DIR}/script

after_script:
  - source ${LP3D_CI_DIR}/after_script

stages:
  - Build and Package
  - GitHub Release

jobs:
 fast_finish: true
 include:
  - stage: Build and Package
    env: LP3D_BUILD_ARCH2017=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_FEDORA25=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_XENIAL=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_MACOS=true
    os: osx
    compiler: clang
  - stage: Build and Package
    env: LP3D_COMPILE_SOURCE=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_COMPILE_SOURCE=true
    os: osx
    compiler: clang
  - stage: GitHub Release
    env: LP3D_DEPLOY_PACKAGES=true
    script: source ${LP3D_CI_DIR}/releases
    deploy:
      provider: releases
      name: $LP3D_RELEASE_NAME
      api_key:
        secure: GRl0LOJ8M5ow1qik8t2+tJsqMDo53v/TRfxprWg5C+3DR3ny/CgR5mODMtpR4LgSyMeD5yhGovxHAbzgUyutne9PT0BagI8zdt/ZMqcLnvPQyzJlhfy3t2TVcJRoVXcoUUF0ZJHrpr9WD8C7xnjMp7w/j+HThQuX+8CD3gCwZhYkDRuNgtJY/PT+nwITjC4WJuF0xxYOyLJROebQZ1LJ24HY0zVtg+JJZPslkQHgoBg/ozO8JNXgYaYe3VgcyQSnUMqE/SjMBGYMR9RlNwYXCJLeYHiY3fej33z7UPZOH/kPQ8RhKpJi9qqOTtYj38dTxmpiJjOJ4SyeKXvsyymc5ekwSdlJe6rVWKKAXFMegH/4i3Nk8HKmfxMPLklprusFEMQo2CdA5UeNRuWJ/HfDpywbQwFLC6ThNZcS6wqOqf2Rzy6QRNFWlH9eJoiSMyQRVTFGwQ3bf2MXXJSloFuxRpGYoejWt36O+rNZnTR6+Xz1r2KyaaFizCGen082klzmfdoCl0mh+m9Jix7ypzgNBKISFI5DTbjr6Qt+D5dVdp5PWGBAbhTd6JtcG64P9fDUWq5X9ypFj6Jb1626sHFlYQKCSX+lEpjbd4UTSbTxO35NMTO1g90xKMJeIpvsCwm9DcWl+jGmt9cwSHxTQuWkeEaUcoywYvA4kTjIpDuIaR8=
      file_glob: true
      file: $LP3D_RELEASE_DIR/*
      overwrite: true
      skip_cleanup: true
      on:
        repo: trevorsandy/lpub3d-ci
        condition: $LP3D_DEPLOY_PKG = yes

notifications:
  email:
    on_success: never
    on_failure: always
