language: cpp
sudo: required
dist: trusty

cache: ccache

git:
  depth: 200

branches:
  only:
  - master

matrix:
 fast_finish: true
 include:
  - os: linux
    compiler: gcc
    env:
     - QT_BASE=59
  - os: osx
    compiler: clang
    env:
     - QT_BASE=59

before_install:
  # Skip build if the commit message contains [skip travis] or [travis skip]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] detected, exiting."
      && exit 0 || true
  # Create package if commit message contains [create pkg]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[create pkg\]'
      && echo "[create pkg] detected."
      && export LP3D_CREATE_PKG=yes || true
  # Add private qt repositories
  - if [[ "$QT_BASE" = "52" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt521-trusty -y; fi
  - if [[ "$QT_BASE" = "53" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi
  - if [[ "$QT_BASE" = "54" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - if [[ "$QT_BASE" = "55" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [[ "$QT_BASE" = "56" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [[ "$QT_BASE" = "58" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty  -y; fi
  - if [[ "$QT_BASE" = "59" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y; fi
  # Update repository index and download package dependencies/docker-engine if required
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  # Install qt5 on Linux
  - if [[ "$QT_BASE" = "52" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt52base; source /opt/qt52/bin/qt52-env.sh; fi
  - if [[ "$QT_BASE" = "53" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt53base; source /opt/qt53/bin/qt53-env.sh; fi
  - if [[ "$QT_BASE" = "54" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt54base; source /opt/qt54/bin/qt54-env.sh; fi
  - if [[ "$QT_BASE" = "55" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; fi
  - if [[ "$QT_BASE" = "56" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
  - if [[ "$QT_BASE" = "58" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh; fi
  - if [[ "$QT_BASE" = "59" && "$TRAVIS_OS_NAME" = "linux" && ! "$LP3D_CREATE_PKG" = "yes" ]]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
  # Install qt5 on MacOS, clone lpub3d_macos_3rd party repository and download LDraw library archive files
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ "$QT_BASE" = "55" ]; then
        brew install qt55;
        brew link --force qt55;
      else
        brew install qt5;
        brew link --force qt5;
      fi;
      git clone https://github.com/trevorsandy/lpub3d_macos_3rdparty.git ../lpub3d_macos_3rdparty;
      wget http://www.ldraw.org/library/updates/complete.zip -O mainApp/extras/complete.zip
      wget http://www.ldraw.org/library/unofficial/ldrawunf.zip -O mainApp/extras/lpub3dldrawunf.zip
    fi
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ "$LP3D_CREATE_PKG" = "yes" ]; then
        curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -;
        echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list;
        sudo apt-get update -qq;
        sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine;
        docker version;
        sudo pip install docker-compose;
        docker-compose version;
      fi;
    fi

script:
  # Build distributions package or just compile the code
  - if [ "$LP3D_CREATE_PKG" = "yes" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker-compose -f builds/linux/docker-compose/docker-compose-ubuntu_xenial.yml run --rm lpub3d-ci; fi;
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then source builds/macx/CreateDmg.sh; fi;
    else
     qmake -v;
     qmake -r;
     make;
    fi

after_script:
  - if [ "$LP3D_CREATE_PKG" = "yes" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        export LP3D_Download_DebPackage=`ls builds/linux/docker-compose/LPub3D_*.deb`;
        export LP3D_Update_DebPackage=`ls builds/linux/docker-compose/LPub3D-UpdateMaster_*.deb`;
      fi
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        export LP3D_Download_DmgPackage=`ls builds/linux/docker-compose/LPub3D_*.deb`;
        export LP3D_Update_DmgPackage=`ls builds/linux/docker-compose/LPub3D-UpdateMaster_*.deb`;
      fi
      env | grep -P 'LP3D*';
    fi

deploy:
  provider: releases
  api_key:
    secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
  file: $LP3D_Download_DebPackage
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    condition: $LP3D_CREATE_PACKAGE = true

notifications:
  email:
    on_success: never
    on_failure: always
