language: cpp
sudo: required
dist: trusty

git:
  depth: 200

cache:
  ccache: true
  directories:
  - ${LP3D_LDRAW_DIR}
  - ${LP3D_DIST_DIR_BASE}

env:
  global:
    - LP3D_QT_BASE=59
    - LP3D_LDRAW_DIR=${HOME}/ldraw
    - LP3D_BUILD_FOLDER=${TRAVIS_BUILD_DIR}
    - LP3D_RELEASES_DIR=${LP3D_BUILD_FOLDER}/builds/releases
    - LP3D_LOGS_DIR=${LP3D_RELEASES_DIR}/logs
    - LP3D_UPDATES_DIR=${LP3D_RELEASES_DIR}/updates
    - LP3D_DOWNLOADS_DIR=${LP3D_RELEASES_DIR}/downloads
    - LP3D_3RD_BUILD_FOLDER=${LP3D_BUILD_FOLDER}/..
    - LP3D_DIST_DIR_BASE=${LP3D_3RD_BUILD_FOLDER}/lpub3d_3rdparty_base
    - LP3D_COMPOSE_DIR=builds/linux/docker-compose
    - LP3D_CI_DIR=builds/utilities/ci
    - LP3D_SECURE_DIR=builds/utilities/ci/secure
    - LP3D_CI_SCRIPT_DIR=builds/utilities/ci/travis
    - LP3D_DROPBOX_RELEASES_DIR=travis-ci/releases
    - LP3D_DROPBOX_LOGS_DIR=${LP3D_DROPBOX_RELEASES_DIR}/logs
    - LP3D_DROPBOX_UPDATES_DIR=${LP3D_DROPBOX_RELEASES_DIR}/updates
    - LP3D_DROPBOX_DOWNLOADS_DIR=${LP3D_DROPBOX_RELEASES_DIR}/downloads
    - LP3D_RELEASE_LABEL="LPub3D $(date +'%d.%m.%Y')"
    - secure: "borWKC2OLFOt13ZlxkLtVNfWMGfW3vtlivpJdNu7g5ZiIeySLO4641U7xY1f3c5eFtnEif5XtB4WrKI7M+eXypJl7qs/Ds6nauSKOP3XCw8yNjxZomU1DD8dMWaQibe8b3rFC5emFFZ/KtG438C4IPHSkd2paaGYyXcGWMaPZLsAuReW78H0eZTvAkNn17kusZ11rwtk5avzZKm/2eD95z7ac2RCa+pZTKUGMK+aq3GM3iplyV0Kopi/p/jYvnYaxqW4/HD6+0NMiWs6YlVv9m5eMmUEwbh2VFW7nl/hinUf9xGlLuzQj5mIlxn2moQXA0I526kObm7zELLZp+OR4cwC+oMH5CHXCopBe0jy6KAc8/k7nZ3205llT0VrtBw5zXV1LMDut4hsefcyEilT1kRnFpQjapFd61a/Pd9iSZwl/KBXj6pmE+wkEK65GTgUA7JIVtp+ILz+oapwjDdyYguqU8WF31OiJIP5FyRmh/VF9azsJv93WVzbER8BQho5ZvdyHLWs+GSt807mKEqrpWvaukYYR2jB4T0K54M25e4wMKYU25DEiltTP1F017UIlGEqLWy0nNltGGPBQukp6rg4XbPInIHIQoydklgaHOMuARDstzncnIEViNlXULJKdnXiPvMgBODIo0aZFHMxvYufBDgycj0ZHLfTb2+/Qto="
    - secure: "O14SvpHHE7mBCahNrI/5DQjBow46T5jitYDBqOLVji0GgOdRXAa3BC+U6fF3YWuQhW24484M4yDXA3zNlXExeXwyqVSzmdOSgdj9Fasz+T4pDeAUKF5mJKpmQHHychNQN0+GfsK1csxNNG0/qjeZXbqFmQ15vWYbsPGwfDtDlQETE0xz2n0K4Np2gi/FF68XzXJPjIIHIysXGYEJsMNf15njgjID2/CzVWZt0ZAQREw4nB+telZunysj+NBtzEk5TkRImMsg84Q1ZdqVJBQpAccbLT6qzduSLiLkjTcMqOFc5DW9IKC7tvCAIxNCFfBWSuNY7A1c/el241wxfWPsn9TGHdRTbRTPezY+dKULDoj0TWCh1CEcrXrRU3Kbin2IltEYcGcfOnqnlz4i97e5pSN+mjOUTs0ijHLWGRygUDILICcVxKyqkYe6T0EGh+QNhfVGT6g0ssDn7u1+XqEBmP3+Kc71+NK13cG/aRVyUPAQigaNo5zGl0iux/QVJoREHO3CX6HLLL+wmj+A3UIYcRYbH4PuhqmpvECe5oGz5TvMFV7G51XyAvPyBgeBZWhR2m2f85aiiAiWZBMiOh0m+TBdWEX3vQ1HY/qhsyAYklpReVt48ngQoVWOACq0mcXQOeRcixjpEeRBA4IwXUmR21xaUtdMioMKWZuRhF1upOI="

addons:
  ssh_known_hosts: trevorsandy@frs.sourceforge.net

stages:
  - name: Prepare Release Store
    if: tag =~ ^(?!$)(?:v[0-9]+\.[0-9]+\.[0-9]+_?[^\W]*)?$
  - name: Build and Package
  - name: GitHub Release
    if: tag =~ ^(?!$)(?:v[0-9]+\.[0-9]+\.[0-9]+_?[^\W]*)?$

before_install:
  - source ${LP3D_CI_SCRIPT_DIR}/before_install

install:
  - source ${LP3D_CI_SCRIPT_DIR}/install

script:
  - source ${LP3D_CI_SCRIPT_DIR}/script

after_script:
  - source ${LP3D_CI_SCRIPT_DIR}/after_script

jobs:
 fast_finish: true
 include:
  - stage: Prepare Release Store
    env: LP3D_DEPLOY_PACKAGES=true
    os: linux
    compiler: gcc
    script: source ${LP3D_CI_SCRIPT_DIR}/prepare_store
  - stage: Build and Package
    env: LP3D_BUILD_ARCH2017=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_FEDORA25=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_XENIAL=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_MACOS=true
    os: osx
    compiler: clang
  - stage: Build and Package
    env: LP3D_COMPILE_SOURCE=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_COMPILE_SOURCE=true
    os: osx
    compiler: clang
  - stage: GitHub Release
    env: LP3D_DEPLOY_PACKAGES=true
    script: source ${LP3D_CI_SCRIPT_DIR}/releases
    deploy:
      - provider: releases
        name: $LP3D_RELEASE_LABEL
        api_key:
          secure: GRl0LOJ8M5ow1qik8t2+tJsqMDo53v/TRfxprWg5C+3DR3ny/CgR5mODMtpR4LgSyMeD5yhGovxHAbzgUyutne9PT0BagI8zdt/ZMqcLnvPQyzJlhfy3t2TVcJRoVXcoUUF0ZJHrpr9WD8C7xnjMp7w/j+HThQuX+8CD3gCwZhYkDRuNgtJY/PT+nwITjC4WJuF0xxYOyLJROebQZ1LJ24HY0zVtg+JJZPslkQHgoBg/ozO8JNXgYaYe3VgcyQSnUMqE/SjMBGYMR9RlNwYXCJLeYHiY3fej33z7UPZOH/kPQ8RhKpJi9qqOTtYj38dTxmpiJjOJ4SyeKXvsyymc5ekwSdlJe6rVWKKAXFMegH/4i3Nk8HKmfxMPLklprusFEMQo2CdA5UeNRuWJ/HfDpywbQwFLC6ThNZcS6wqOqf2Rzy6QRNFWlH9eJoiSMyQRVTFGwQ3bf2MXXJSloFuxRpGYoejWt36O+rNZnTR6+Xz1r2KyaaFizCGen082klzmfdoCl0mh+m9Jix7ypzgNBKISFI5DTbjr6Qt+D5dVdp5PWGBAbhTd6JtcG64P9fDUWq5X9ypFj6Jb1626sHFlYQKCSX+lEpjbd4UTSbTxO35NMTO1g90xKMJeIpvsCwm9DcWl+jGmt9cwSHxTQuWkeEaUcoywYvA4kTjIpDuIaR8=
        file_glob: true
        file: $LP3D_DOWNLOADS_DIR/*
        overwrite: true
        skip_cleanup: true
        on:
          repo: trevorsandy/lpub3d-ci
          branch: $TRAVIS_BRANCH
          condition: $LP3D_DEPLOY_PKG = yes
      - provider: script
        skip_cleanup: true
        script: rsync -r --quiet ${LP3D_DOWNLOADS_DIR}/* ${SECURE_SF_DOWNLOAD_CONNECT}/${$LP3D_VERSION}/
        on:
          branch: $TRAVIS_BRANCH
          condition: $LP3D_DEPLOY_SF_PKG = yes
      - provider: script
        skip_cleanup: true
        script: rsync -r --quiet ${LP3D_UPDATES_DIR}/* ${SECURE_SF_UDPATE_CONNECT}/
        on:
          branch: $TRAVIS_BRANCH
          condition: $LP3D_DEPLOY_PKG = yes
          condition: $LP3D_DEPLOY_SF_PKG = yes;

notifications:
  email:
    on_success: never
    on_failure: always
