language: cpp
sudo: required
dist: trusty

git:
  depth: 200

cache:
  ccache: true
  directories:
  - ${LP3D_LDRAW_DIR}
  - ${LP3D_DIST_DIR_BASE}

env:
  global:
    - LP3D_QT_BASE=59
    - LP3D_LDRAW_DIR=${HOME}/ldraw
    - LP3D_BUILD_FOLDER=${TRAVIS_BUILD_DIR}
    - LP3D_RELEASES_DIR=${LP3D_BUILD_FOLDER}/builds/releases
    - LP3D_LOGS_DIR=${LP3D_RELEASES_DIR}/logs
    - LP3D_UPDATES_DIR=${LP3D_RELEASES_DIR}/updates
    - LP3D_DOWNLOADS_DIR=${LP3D_RELEASES_DIR}/downloads
    - LP3D_3RD_BUILD_FOLDER=${LP3D_BUILD_FOLDER}/..
    - LP3D_DIST_DIR_BASE=${LP3D_3RD_BUILD_FOLDER}/lpub3d_3rdparty_base
    - LP3D_COMPOSE_DIR=builds/linux/docker-compose
    - LP3D_CI_DIR=builds/utilities/ci
    - LP3D_SECURE_DIR=builds/utilities/ci/secure
    - LP3D_CI_SCRIPT_DIR=builds/utilities/ci/travis
    - LP3D_DROPBOX_RELEASES_DIR=travis-ci/releases
    - LP3D_DROPBOX_LOGS_DIR=${LP3D_DROPBOX_RELEASES_DIR}/logs
    - LP3D_DROPBOX_UPDATES_DIR=${LP3D_DROPBOX_RELEASES_DIR}/updates
    - LP3D_DROPBOX_DOWNLOADS_DIR=${LP3D_DROPBOX_RELEASES_DIR}/downloads
    - LP3D_RELEASE_LABEL="LPub3D $(date +'%d.%m.%Y')"
    - secure: "aOvx3tG/0xA4yFgttNdbPATfZruWpsjkcJSGdtTy4ICgTAvXKb0lUT3oeG3RNIeLnG1ENjzBdzhlYYFJ5+JWi53DHzw9BEfPkwUsJzjqprd2pWqDlp0gIWoZ/lFg1PNSERDknw7ROKBBzJ1CnnNNZuFp0RM7D7ijaqB11e/sodEdqiYrcMvDIpgp2/qp13azvSytYgWMCGH1JFRiTgKdnaJDWIVA7zJliuH6MOWzVBcHGEBD8Zk8fNeQRUPl7LEWiPSoLOcTkuY22Q1xZkMpkQ6066RRrPavJtjeY6II20k82pFeR411jufuUN+15z+eKqa+b8ZaRLbSKCNsrD5xELTrAks9omML6DIgDfr5+hfW5LGit6AJxjnKgF/Si0uvDkvkws5Mtb0wGLDZwL8oYw6o6uuMzaYBKijaQ1nU3/qYw8f2GAuZVVlvX7BqKTaA7D+Y/SNLBEM4YEN0HfrHpCUiSRTzDURplaTuhovgb8hK1f4nFJjt3FsQxsstBjlmE4rUuNBYb6H8ST/Y7m70guJ6Svn9oEdMJD+cXmSuDuz2hPzJDacvwgk94Lyg+azcQCxUcXKOguAbWObcUqJclsbnKCjcghqHOhSmD7hmC81u6vyfwkJKn0M8884NmHi9AiHCkCnlMJw/aFfdL2mQJDLpjhewMkaWnlhRHgOgKhU="
    - secure: "c/wWajidzTZ4knDEzsZIEpPo9xglrXqEJ198LlUP9SglUIbrTDQgnpWqU2gH7J2WiyGMdYFqZJI+Z4crkaQvN4154Ucg2rMyzMIxkjJCR+T/geJ45WvJ6k4PlsecLEjsqA74qo5Fr5BAF0UKN6dB3sVfMTmC92S9Uas6vDHZR8pI4sJo2riIzAhNPKi8gTZ+QmFUkvuY33K5FrLQC3hYFta6Neg1OpdNiRWVjU7mVRi8+TbQ7vNSicaK1dQOmct80zx8SgdZ9fJTe8PQVCQUccDZ6yGONJp02maHWTq2UrDJMU8krOd3SEz9zJr4rU3P1qUISxtXiimWp9B5PowTL1qohZTOthApr2nvpULQUOKm4fkpI+HTCpLWj6wQdOuD+gEgn4FcuGyhx1iozUZj+w92Jc/ok8ldW2Yytgvs2mLAEPUppL+mLvWr8YjEjuTxrnqUF5ATZDrAfmxP0oYtuv2+XqQkJXk2wnJc5opcMp6tsGfCwqgd9ifm6whpDry8HhTCjRoefrpsjRN0HBvqNy/MqxqnrZt3wT3X/heC69VvVUa8I2vl8Pwqj8jzEs9eReUrQQIrIoeGqsNa36lOuKe7tumAfkVOO6cfrduhz0vwVK0ABMIsYIQNqGl7SmkhO4yqMNbFZcBqA8Yj3LRDhGYPhs4qG6u9XtZItt25qEU="

addons:
  ssh_known_hosts: trevorsandy@frs.sourceforge.net

stages:
  - name: Prepare Release Store
    if: tag =~ ^(?!$)(?:v[0-9]+\.[0-9]+\.[0-9]+_?[^\W]*)?$
  - name: Build and Package
  - name: GitHub Release
    if: tag =~ ^(?!$)(?:v[0-9]+\.[0-9]+\.[0-9]+_?[^\W]*)?$

before_install:
  - source ${LP3D_CI_SCRIPT_DIR}/before_install

install:
  - source ${LP3D_CI_SCRIPT_DIR}/install

script:
  - source ${LP3D_CI_SCRIPT_DIR}/script

after_script:
  - source ${LP3D_CI_SCRIPT_DIR}/after_script

jobs:
 fast_finish: true
 include:
  - stage: Prepare Release Store
    env: LP3D_DEPLOY_PACKAGES=true
    os: linux
    compiler: gcc
    script: source ${LP3D_CI_SCRIPT_DIR}/prepare_store
  - stage: Build and Package
    env: LP3D_BUILD_ARCH2017=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_FEDORA25=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_XENIAL=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_BUILD_MACOS=true
    os: osx
    compiler: clang
  - stage: Build and Package
    env: LP3D_COMPILE_SOURCE=true
    os: linux
    compiler: gcc
  - stage: Build and Package
    env: LP3D_COMPILE_SOURCE=true
    os: osx
    compiler: clang
  - stage: GitHub Release
    env: LP3D_DEPLOY_PACKAGES=true
    script: source ${LP3D_CI_SCRIPT_DIR}/releases
    deploy:
      - provider: releases
        name: $LP3D_RELEASE_LABEL
        api_key:
          secure: GRl0LOJ8M5ow1qik8t2+tJsqMDo53v/TRfxprWg5C+3DR3ny/CgR5mODMtpR4LgSyMeD5yhGovxHAbzgUyutne9PT0BagI8zdt/ZMqcLnvPQyzJlhfy3t2TVcJRoVXcoUUF0ZJHrpr9WD8C7xnjMp7w/j+HThQuX+8CD3gCwZhYkDRuNgtJY/PT+nwITjC4WJuF0xxYOyLJROebQZ1LJ24HY0zVtg+JJZPslkQHgoBg/ozO8JNXgYaYe3VgcyQSnUMqE/SjMBGYMR9RlNwYXCJLeYHiY3fej33z7UPZOH/kPQ8RhKpJi9qqOTtYj38dTxmpiJjOJ4SyeKXvsyymc5ekwSdlJe6rVWKKAXFMegH/4i3Nk8HKmfxMPLklprusFEMQo2CdA5UeNRuWJ/HfDpywbQwFLC6ThNZcS6wqOqf2Rzy6QRNFWlH9eJoiSMyQRVTFGwQ3bf2MXXJSloFuxRpGYoejWt36O+rNZnTR6+Xz1r2KyaaFizCGen082klzmfdoCl0mh+m9Jix7ypzgNBKISFI5DTbjr6Qt+D5dVdp5PWGBAbhTd6JtcG64P9fDUWq5X9ypFj6Jb1626sHFlYQKCSX+lEpjbd4UTSbTxO35NMTO1g90xKMJeIpvsCwm9DcWl+jGmt9cwSHxTQuWkeEaUcoywYvA4kTjIpDuIaR8=
        file_glob: true
        file: $LP3D_DOWNLOADS_DIR/*
        overwrite: true
        skip_cleanup: true
        on:
          repo: trevorsandy/lpub3d-ci
          branch: $TRAVIS_BRANCH
          condition: $LP3D_DEPLOY_PKG = yes
      - provider: script
        skip_cleanup: true
        script: rsync -r --quiet ${LP3D_DOWNLOADS_DIR}/* ${LP3D_SF_DOWNLOAD_CONNECT}/${$LP3D_VERSION}/
        on:
          branch: $TRAVIS_BRANCH
          condition: $LP3D_DEPLOY_SF_PKG = yes
      - provider: script
        skip_cleanup: true
        script: rsync -r --quiet ${LP3D_UPDATES_DIR}/* ${LP3D_SF_UDPATE_CONNECT}/
        on:
          branch: $TRAVIS_BRANCH
          condition: $LP3D_DEPLOY_PKG = yes
          condition: $LP3D_DEPLOY_SF_PKG = yes;


notifications:
  email:
    on_success: never
    on_failure: always
