# Build and check LPub3D x86 and x86_64 architectures unsing Qt/MinGW platform
version: 'LPub3D-AV-2.1.0.{build}'

clone_folder: c:\projects\lpub3d-ci

# skip automatic cloning because we want to restore cached items in the clone directory first
clone_script: echo skip

# we're caching:
# LDraw parts library - used for testing renderers
# Qt5 for MinGW i386 and x86_64 in lp3d_librepo - enable building MinGW and MSBild in same job
# Built renderers
cache:
 - '$(APPVEYOR_BUILD_FOLDER)\LDraw'
 - '$(APPVEYOR_BUILD_FOLDER)\${lp3d_librepo}'
 - '$(APPVEYOR_BUILD_FOLDER)\$(LP3D_DIST_DIR)'

shallow_clone: true

image: Visual Studio 2017

branches:
  only:
   - master

configuration: release

matrix:
  fast_finish: true

environment:
  LP3D_PACKAGE: LPub3D
  LP3D_PACKAGE_PATH: builds\windows\$(configuration)
  LP3D_DIST_DIR: lpub3d_windows_3rdparty
  LP3D_DIST_DIR_PATH: $(APPVEYOR_BUILD_FOLDER)\$(LP3D_DIST_DIR)
  LP3D_QT32_MSYS2: c:\msys64\MINGW32\bin
  LP3D_QT64_MSYS2: c:\msys64\MINGW64\bin
  LP3D_QT32_LIBS: mingw-w64-i686-qt5-5.9.2-2-any.pkg.tar.xz
  LP3D_QT64_LIBS: mingw-w64-x86_64-qt5-5.9.2-2-any.pkg.tar.xz
  lp3d_librepo: lpub3d_mingw-Qt5_libs
  lp3d_librepodir: /c/projects/$(APPVEYOR_PROJECT_NAME)/$(lp3d_librepo)

# Build package if commit message contains [build pkg]
# Parse the commit message for 3rd party build override
# As 3rd party items are not expected to change often
# We cache them to speed up the build. If/when it is necessary
# to build one of the items, we signa with 1 in the commit message
# The format is [build pkg 1 1 1] to build all 3rd party itmes.
# The first position is LDGlite, the second is LDView and the
# third is LPub3D_Trace (POV-Ray). Alternatively you may choose
# to build only one of the items in which case the settings would
# be ...1 0 0 to only build the LDGlite.
init:
 - ps: write-host "Building ${env:LP3D_PACKAGE} x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:LP3D_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:LP3D_BUILD_PKG = "yes"
        $env:LP3D_DEPLOY_PKG = $true
      }
 - ps: |
      If ($env:LP3D_BUILD_PKG -eq "yes") {
        If ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match '([^(build|deploy) pkg]\s?\d?\s?\d?)]$') {
          $env:LP3D_BUILD_LDGLITE = $matches[1].substring(0,1)
          $env:LP3D_BUILD_LDVIEW = $matches[1].substring(2,1)
          $env:LP3D_BUILD_TRACE = $matches[1].substring(4,1)
          $env:LP3D_LDGLITE = ${env:LP3D_DIST_DIR_PATH}/ldglite-1.3;
          $env:LP3D_LDVIEW = ${env:LP3D_DIST_DIR_PATH}/ldview-4.3;
          $env:LP3D_LPUB3D_TRACE = ${env:LP3D_DIST_DIR_PATH}/lpub3d_trace_cui-3.8;
        }
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[clear avcache]")) {
        write-host "[clear avcache] detected."

        $apiUrl = 'https://ci.appveyor.com/api'
        $token = 'h2o1p08rkt8jgen5f0ke'
        $headers = @{
          "Authorization" = "Bearer $token"
          "Content-type" = "application/json"
        }

        $accountName = $env:APPVEYOR_ACCOUNT_NAME
        $projectSlug = $env:APPVEYOR_PROJECT_SLUG

        $env:APPVEYOR_CACHE_SKIP_RESTORE  = "true"
        Invoke-RestMethod -Uri "$apiUrl/projects/$accountName/$projectSlug/buildcache" -Headers $headers -Method DELETE

        Write-Output "Build cache cleared."
      }
 - ps: Get-ChildItem Env:LP3D_* | Sort-Object name

# This is where we install MinGW Qt5 for x86 and x86_64 builds. The Qt builds are necessarey because we are using VS image which
# does not have Qt x86 but it does have Msys2/Mingw. As there is no x86_64 MinGW Qt, we build both the x86 and x86_64 architectures.
# The source for these items are cached but if not then they are downloded - I have prepared a special archive with only release binaries
# that are about 33MB for each archive. After setting up these items, we proceed to fetch the commit that triggered the AppVeyor build.
# We don't use git clone because the 'clone_directory' is not empty (restored cached components were added in previous steps) - so the
# git clone command will fail. Instead we use fetch and checkout to pretty much replicate the same behaviour as the default git clone.
# This includes setting the clone depth, and fetching the last commit and previous tags. Lastly, we manage 3rd party items cache -
# deleting a component will trigger a new build.
install:
 - cmd: git init %APPVEYOR_BUILD_FOLDER%
 - cmd: cd %APPVEYOR_BUILD_FOLDER%
 - cmd: git remote add origin https://github.com/%APPVEYOR_REPO_NAME%.git
 - cmd: git fetch -qfup --depth=200 origin +%APPVEYOR_REPO_BRANCH% +refs/tags/*:refs/tags/*
 - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
 - cmd: bash -lc "if ! test -d ${lp3d_librepodir}; then curl -sL -o ${lp3d_librepo}.tar.gz https://github.com/trevorsandy/${lp3d_librepo}/archive/master.tar.gz; fi"
 - cmd: bash -lc "if ! test -d ${lp3d_librepodir} && test -f ${lp3d_librepo}.tar.gz; then mkdir -p ${lp3d_librepodir} && tar -xzf ${lp3d_librepo}.tar.gz -C ${lp3d_librepodir} --strip-components=1; fi"
 - cmd: bash -lc "if ! test -d ${lp3d_librepodir}; then echo repository ${lp3d_librepodir} not found; else echo library repository available at ${lp3d_librepodir}; fi"
 - cmd: C:\msys64\usr\bin\bash -lc "cd ${lp3d_librepodir}/qt-5.9.2-2-release; pacman -U --needed --noconfirm ${LP3D_QT32_LIBS} ${LP3D_QT64_LIBS} > CreateQtBuildEnv.log 2>&1"
 - cmd: bash -lc "if test "$LP3D_BUILD_LDGLITE" = "1" && test -d $LP3D_LDGLITE; then rm -rf $LP3D_LDGLITE && echo "cached $LP3D_LDGLITE deleted"; fi"
 - cmd: bash -lc "if test "$LP3D_BUILD_LDVIEW" = "1" && test -d $LP3D_LDVIEW; then rm -rf $LP3D_LDVIEW && echo "cached $LP3D_LDVIEW deleted"; fi"
 - cmd: bash -lc "if test "$LP3D_BUILD_TRACE" = "1" && test -d $LP3D_LPUB3D_TRACE; then rm -rf $LP3D_LPUB3D_TRACE && echo "cached $LP3D_LPUB3D_TRACE deleted"; fi"

build_script:
 - ps: |
      write-host "  Distribution Directory.....[$env:LP3D_PACKAGE_PATH]"
      write-host "  Working Directory..........[$PWD]"
      If ($env:LP3D_BUILD_PKG -eq "yes") {
        cmd.exe /c builds\windows\AutoBuild.cmd -all -3rd -ins -chk 2`>`&1
        $env:LP3D_ARTEFACT_ITEM_COUNT = (Get-ChildItem -Path $env:LP3D_PACKAGE_PATH -Recurse).count
        write-host "`n  Build Archive Item Count...[$env:LP3D_ARTEFACT_ITEM_COUNT]"
        (Get-ChildItem -Path $env:LP3D_PACKAGE_PATH -Recurse | Select-Object -ExpandProperty FullName | ft -hidetableheaders)
      } Else {
        cmd.exe /c builds\windows\AutoBuild.cmd -all -3rd -chk 2`>`&1
      }

test: off

after_build:
 - ps: |
      If ($env:LP3D_BUILD_PKG -eq "yes" -And [int]$env:LP3D_ARTEFACT_ITEM_COUNT -gt 77) {
        cmd.exe /c builds\windows\CreateExePkg.cmd 2`>`&1
        $Sv = git describe --tags --long
        $Sc = git rev-list HEAD --count
        $Sd = Get-Date -format yyyyMMdd
        $env:LP3D_BUILD_VERSION =($Sv.substring(0,$Sv.lastIndexOf('-'))+"."+$Sc+"_"+$Sd).replace("v","").replace("-",".")
        $env:LP3D_BUILD_PACKAGE = "${env:LP3D_PACKAGE}-Any-${env:LP3D_BUILD_VERSION}"
        $env:LP3D_BUILD_TARGET = "${env:LP3D_PACKAGE_PATH}\${env:LP3D_BUILD_PACKAGE}"
        $env:LP3D_BUILD_DOWNLOAD_TARGET = "${env:LP3D_BUILD_TARGET}\${env:LP3D_PACKAGE}_Download"
        $env:LP3D_BUILD_UPDATE_TARGET = "${env:LP3D_BUILD_TARGET}\${env:LP3D_PACKAGE}_Update"
        Get-ChildItem Env:LP3D_BUILD_* | Sort-Object name
        $root = Resolve-Path .\${env:LP3D_BUILD_DOWNLOAD_TARGET}; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName ${env:LP3D_PACKAGE}-download-package }
        $root = Resolve-Path .\${env:LP3D_BUILD_UPDATE_TARGET};   [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName ${env:LP3D_PACKAGE}-update-package }
      }

deploy:
 - provider: GitHub
   repository: trevorsandy/lpub3d-ci
   description: '$(LP3D_PACKAGE) - An LDraw™ editor for LEGO® style digital building instructions.'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   release: $(LP3D_BUILD_PACKAGE)
   artifact: $(LP3D_PACKAGE)-download-package
   prerelease: true
   force_update: true
   on:
    branch: master
    lp3d_deploy_pkg: true
