# $ docker-compose -f docker-compose-linux.yml run --rm [archlinux_2017.10.01|fedora_25|ubuntu_xenial]
# $ docker-compose -f docker-compose-linux.yml build --no-cache [archlinux_2017.10.01|fedora_25|ubuntu_xenial]
version: '3'
services:
  archlinux_2017.10.01:
    image: "trevorsandy/lpub3d-ci:archlinux_2017.10.01"
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-archlinux_2017.10.01
    volumes:
     - .:/buildpkg

  fedora_25:
    image: "trevorsandy/lpub3d-ci:fedora_25"
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-fedora_25
    volumes:
     - .:/buildpkg

  ubuntu_xenial:
    image: "trevorsandy/lpub3d-ci:ubuntu_xenial"
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-ubuntu_xenial
    volumes:
     - .:/buildpkg
